Set exit code so system tests show not passing
To use system tests correctly in workflow/autograder, need to
set a non zero exit code on system tests failures.  Now
the autograder detects when system tests are not passing
and does the correct thing.

diff --git a/scripts/run-system-tests b/scripts/run-system-tests
--- a/scripts/run-system-tests
+++ b/scripts/run-system-tests
@@ -54,11 +54,14 @@ do
     fi
 done
 
+# display final result of tests, give explicit non-zero exit code on failure so workflow detect failed tests
 if [ ${passed} -eq ${NUM_TESTS} ]
 then
     echo -e "${GREEN}===============================================================================${NORMAL}"
     echo -e "${GREEN}All system tests passed    ${NORMAL} (${passed} tests passed of ${NUM_TESTS} system tests)"
+    exit 0
 else
     echo -e "${RED}===============================================================================${NORMAL}"
     echo -e "${RED}System test failures detected${NORMAL} (${passed} tests passed of ${NUM_TESTS} system tests)"
+    exit 1
 fi
